# Generated by Django 5.1.6 on 2025-02-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('beta', models.FloatField()),
                ('sigma', models.FloatField()),
                ('gamma', models.FloatField()),
                ('nu', models.FloatField()),
                ('mu', models.FloatField()),
                ('s_peak', models.FloatField()),
                ('e_peak', models.FloatField()),
                ('i_peak', models.FloatField()),
                ('r_peak', models.FloatField()),
                ('v_peak', models.FloatField()),
                ('d_peak', models.FloatField()),
            ],
        ),
    ]
