# Generated by Django 5.1.6 on 2025-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modeling', '0002_simulationresult_parameters_simulationresult_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='d_peak_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='e_peak_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='i_peak_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='r_peak_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='s_peak_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='v_peak_day',
            field=models.FloatField(default=0.0),
        ),
    ]
